"""Regenerate PacketHandler.java for Framework 0.13 (codec based play messages).

The 1.20.1 handler registered `Class + MessageDirection`; Framework 0.13 wants
`id + Class + StreamCodec + handler + PacketFlow`. Every Scorched Guns message
class keeps its 1.20.1 shape, so the codec/handler pair comes from
FrameworkMessageBridge and the direction is the C2S/S2C prefix.
"""
from __future__ import annotations

import os
import re

ROOT = r"E:\mod\scgun-0.5.5-1.21.1-neoforge"
MSG_DIR = os.path.join(ROOT, "src", "main", "java", "top", "ribs", "scguns", "network", "message")
OUT = os.path.join(ROOT, "src", "main", "java", "top", "ribs", "scguns", "network", "PacketHandler.java")

HEADER = '''package top.ribs.scguns.network;

import com.mrcrayfish.framework.api.FrameworkAPI;
import com.mrcrayfish.framework.api.network.FrameworkNetwork;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.resources.ResourceLocation;
%s

/**
 * Registers every Scorched Guns play message on the Framework 0.13 network
 * builder. Generated by tools/gen_packet_handler.py; keep the message classes
 * and this list in sync.
 */
public class PacketHandler {
    private static FrameworkNetwork playChannel;

    private PacketHandler() {
    }

    public static void init() {
        playChannel = FrameworkAPI.createNetworkBuilder(ResourceLocation.fromNamespaceAndPath("scguns", "play"), 1)
%s
                .build();
    }

    public static FrameworkNetwork getPlayChannel() {
        return playChannel;
    }
}
'''

LINE = '                .registerPlayMessage("%s", %s.class, FrameworkMessageBridge.codec(%s.class), FrameworkMessageBridge.handler(%s.class), PacketFlow.%s)'


def snake(name: str) -> str:
    prefix = "c2s" if name.startswith("C2S") else "s2c"
    rest = name[3:].replace("Message", "")
    rest = re.sub(r"(?<!^)(?=[A-Z])", "_", rest).lower()
    return f"{prefix}_{rest}"


def is_play_message(path: str) -> bool:
    """A play message is a class the bridge can drive: it must declare `handle`.

    Scanning the directory alone is not enough - `S2CMessageSyncGunData` lives
    there but is a buffer helper (only `S2CMessageSyncGunData(FriendlyByteBuf)`
    and `toBytes`), it declares no `handle`, and the 1.20.1 PacketHandler never
    registered it. Registering it made `FrameworkMessageBridge` resolve a
    handler for a class that has none.
    """
    src = open(path, encoding="utf-8", errors="replace").read()
    return re.search(r"\bhandle\s*\(", src) is not None


def main() -> None:
    classes, skipped = [], []
    for f in sorted(os.listdir(MSG_DIR)):
        if not f.endswith(".java"):
            continue
        cls = f[:-5]
        (classes if is_play_message(os.path.join(MSG_DIR, f)) else skipped).append(cls)

    ids = {}
    lines = []
    for cls in classes:
        if cls.startswith("C2S"):
            flow = "SERVERBOUND"
        elif cls.startswith("S2C"):
            flow = "CLIENTBOUND"
        else:
            raise SystemExit(f"cannot infer direction for {cls}")
        msg_id = snake(cls)
        if msg_id in ids:
            raise SystemExit(f"duplicate message id {msg_id!r}: {ids[msg_id]} and {cls}")
        ids[msg_id] = cls
        lines.append(LINE % (msg_id, cls, cls, cls, flow))
    body = "\n".join(lines)
    imports = "\n".join(
        "import top.ribs.scguns.network.message.%s;" % cls for cls in classes
    )
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER % (imports, body))
    print(f"wrote {OUT} with {len(classes)} messages")
    for cls in skipped:
        print(f"  skipped (no handle method): {cls}")


if __name__ == "__main__":
    main()
