package top.ribs.scguns.network;

import com.mrcrayfish.framework.api.FrameworkAPI;
import com.mrcrayfish.framework.api.network.FrameworkNetwork;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.resources.ResourceLocation;
import top.ribs.scguns.network.message.C2SMessageAim;
import top.ribs.scguns.network.message.C2SMessageAttachments;
import top.ribs.scguns.network.message.C2SMessageChargeSync;
import top.ribs.scguns.network.message.C2SMessageClearBlueprintRecipe;
import top.ribs.scguns.network.message.C2SMessageEjectCasing;
import top.ribs.scguns.network.message.C2SMessageGunLoaded;
import top.ribs.scguns.network.message.C2SMessageJetpackState;
import top.ribs.scguns.network.message.C2SMessageJetpackThrust;
import top.ribs.scguns.network.message.C2SMessageLeftOverAmmo;
import top.ribs.scguns.network.message.C2SMessageMeleeAttack;
import top.ribs.scguns.network.message.C2SMessageOffhandMelee;
import top.ribs.scguns.network.message.C2SMessagePreFireSound;
import top.ribs.scguns.network.message.C2SMessageReload;
import top.ribs.scguns.network.message.C2SMessageSaveExoSuitUpgrades;
import top.ribs.scguns.network.message.C2SMessageSetBlueprintRecipe;
import top.ribs.scguns.network.message.C2SMessageShoot;
import top.ribs.scguns.network.message.C2SMessageShooting;
import top.ribs.scguns.network.message.C2SMessageStopBeam;
import top.ribs.scguns.network.message.C2SMessageSwapAmmo;
import top.ribs.scguns.network.message.C2SMessageToggleExoSuitPower;
import top.ribs.scguns.network.message.C2SMessageUnload;
import top.ribs.scguns.network.message.C2SMessageUtilityAction;
import top.ribs.scguns.network.message.S2CMessageBeamImpact;
import top.ribs.scguns.network.message.S2CMessageBeamPenetration;
import top.ribs.scguns.network.message.S2CMessageBeamUpdate;
import top.ribs.scguns.network.message.S2CMessageBlood;
import top.ribs.scguns.network.message.S2CMessageBulletTrail;
import top.ribs.scguns.network.message.S2CMessageDualWieldShotCount;
import top.ribs.scguns.network.message.S2CMessageEntityCasingEject;
import top.ribs.scguns.network.message.S2CMessageEntityMuzzleFlash;
import top.ribs.scguns.network.message.S2CMessageGunSound;
import top.ribs.scguns.network.message.S2CMessageHotBarrelSync;
import top.ribs.scguns.network.message.S2CMessageMeleeAttack;
import top.ribs.scguns.network.message.S2CMessageMuzzleFlash;
import top.ribs.scguns.network.message.S2CMessageProjectileHitBlock;
import top.ribs.scguns.network.message.S2CMessageProjectileHitEntity;
import top.ribs.scguns.network.message.S2CMessageRaidFlareBurst;
import top.ribs.scguns.network.message.S2CMessageReload;
import top.ribs.scguns.network.message.S2CMessageRemoveProjectile;
import top.ribs.scguns.network.message.S2CMessageStopBeam;
import top.ribs.scguns.network.message.S2CMessageStopReload;
import top.ribs.scguns.network.message.S2CMessageStunGrenade;
import top.ribs.scguns.network.message.S2CMessageSyncExoSuitUpgrades;
import top.ribs.scguns.network.message.S2CMessageSyncUpgradeRegistry;
import top.ribs.scguns.network.message.S2CMessageTurretBulletTrail;
import top.ribs.scguns.network.message.S2CMessageUpdateAmmo;
import top.ribs.scguns.network.message.S2CMessageUpdateGuns;
import top.ribs.scguns.network.message.S2CShowTotemAnimationMessage;

/**
 * Registers every Scorched Guns play message on the Framework 0.13 network
 * builder. Generated by tools/gen_packet_handler.py; keep the message classes
 * and this list in sync.
 */
public class PacketHandler {
    private static FrameworkNetwork playChannel;

    private PacketHandler() {
    }

    public static void init() {
        playChannel = FrameworkAPI.createNetworkBuilder(ResourceLocation.fromNamespaceAndPath("scguns", "play"), 1)
                .registerPlayMessage("c2s_aim", C2SMessageAim.class, FrameworkMessageBridge.codec(C2SMessageAim.class), FrameworkMessageBridge.handler(C2SMessageAim.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_attachments", C2SMessageAttachments.class, FrameworkMessageBridge.codec(C2SMessageAttachments.class), FrameworkMessageBridge.handler(C2SMessageAttachments.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_charge_sync", C2SMessageChargeSync.class, FrameworkMessageBridge.codec(C2SMessageChargeSync.class), FrameworkMessageBridge.handler(C2SMessageChargeSync.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_clear_blueprint_recipe", C2SMessageClearBlueprintRecipe.class, FrameworkMessageBridge.codec(C2SMessageClearBlueprintRecipe.class), FrameworkMessageBridge.handler(C2SMessageClearBlueprintRecipe.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_eject_casing", C2SMessageEjectCasing.class, FrameworkMessageBridge.codec(C2SMessageEjectCasing.class), FrameworkMessageBridge.handler(C2SMessageEjectCasing.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_gun_loaded", C2SMessageGunLoaded.class, FrameworkMessageBridge.codec(C2SMessageGunLoaded.class), FrameworkMessageBridge.handler(C2SMessageGunLoaded.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_jetpack_state", C2SMessageJetpackState.class, FrameworkMessageBridge.codec(C2SMessageJetpackState.class), FrameworkMessageBridge.handler(C2SMessageJetpackState.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_jetpack_thrust", C2SMessageJetpackThrust.class, FrameworkMessageBridge.codec(C2SMessageJetpackThrust.class), FrameworkMessageBridge.handler(C2SMessageJetpackThrust.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_left_over_ammo", C2SMessageLeftOverAmmo.class, FrameworkMessageBridge.codec(C2SMessageLeftOverAmmo.class), FrameworkMessageBridge.handler(C2SMessageLeftOverAmmo.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_melee_attack", C2SMessageMeleeAttack.class, FrameworkMessageBridge.codec(C2SMessageMeleeAttack.class), FrameworkMessageBridge.handler(C2SMessageMeleeAttack.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_offhand_melee", C2SMessageOffhandMelee.class, FrameworkMessageBridge.codec(C2SMessageOffhandMelee.class), FrameworkMessageBridge.handler(C2SMessageOffhandMelee.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_pre_fire_sound", C2SMessagePreFireSound.class, FrameworkMessageBridge.codec(C2SMessagePreFireSound.class), FrameworkMessageBridge.handler(C2SMessagePreFireSound.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_reload", C2SMessageReload.class, FrameworkMessageBridge.codec(C2SMessageReload.class), FrameworkMessageBridge.handler(C2SMessageReload.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_save_exo_suit_upgrades", C2SMessageSaveExoSuitUpgrades.class, FrameworkMessageBridge.codec(C2SMessageSaveExoSuitUpgrades.class), FrameworkMessageBridge.handler(C2SMessageSaveExoSuitUpgrades.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_set_blueprint_recipe", C2SMessageSetBlueprintRecipe.class, FrameworkMessageBridge.codec(C2SMessageSetBlueprintRecipe.class), FrameworkMessageBridge.handler(C2SMessageSetBlueprintRecipe.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_shoot", C2SMessageShoot.class, FrameworkMessageBridge.codec(C2SMessageShoot.class), FrameworkMessageBridge.handler(C2SMessageShoot.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_shooting", C2SMessageShooting.class, FrameworkMessageBridge.codec(C2SMessageShooting.class), FrameworkMessageBridge.handler(C2SMessageShooting.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_stop_beam", C2SMessageStopBeam.class, FrameworkMessageBridge.codec(C2SMessageStopBeam.class), FrameworkMessageBridge.handler(C2SMessageStopBeam.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_swap_ammo", C2SMessageSwapAmmo.class, FrameworkMessageBridge.codec(C2SMessageSwapAmmo.class), FrameworkMessageBridge.handler(C2SMessageSwapAmmo.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_toggle_exo_suit_power", C2SMessageToggleExoSuitPower.class, FrameworkMessageBridge.codec(C2SMessageToggleExoSuitPower.class), FrameworkMessageBridge.handler(C2SMessageToggleExoSuitPower.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_unload", C2SMessageUnload.class, FrameworkMessageBridge.codec(C2SMessageUnload.class), FrameworkMessageBridge.handler(C2SMessageUnload.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("c2s_utility_action", C2SMessageUtilityAction.class, FrameworkMessageBridge.codec(C2SMessageUtilityAction.class), FrameworkMessageBridge.handler(C2SMessageUtilityAction.class), PacketFlow.SERVERBOUND)
                .registerPlayMessage("s2c_beam_impact", S2CMessageBeamImpact.class, FrameworkMessageBridge.codec(S2CMessageBeamImpact.class), FrameworkMessageBridge.handler(S2CMessageBeamImpact.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_beam_penetration", S2CMessageBeamPenetration.class, FrameworkMessageBridge.codec(S2CMessageBeamPenetration.class), FrameworkMessageBridge.handler(S2CMessageBeamPenetration.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_beam_update", S2CMessageBeamUpdate.class, FrameworkMessageBridge.codec(S2CMessageBeamUpdate.class), FrameworkMessageBridge.handler(S2CMessageBeamUpdate.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_blood", S2CMessageBlood.class, FrameworkMessageBridge.codec(S2CMessageBlood.class), FrameworkMessageBridge.handler(S2CMessageBlood.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_bullet_trail", S2CMessageBulletTrail.class, FrameworkMessageBridge.codec(S2CMessageBulletTrail.class), FrameworkMessageBridge.handler(S2CMessageBulletTrail.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_dual_wield_shot_count", S2CMessageDualWieldShotCount.class, FrameworkMessageBridge.codec(S2CMessageDualWieldShotCount.class), FrameworkMessageBridge.handler(S2CMessageDualWieldShotCount.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_entity_casing_eject", S2CMessageEntityCasingEject.class, FrameworkMessageBridge.codec(S2CMessageEntityCasingEject.class), FrameworkMessageBridge.handler(S2CMessageEntityCasingEject.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_entity_muzzle_flash", S2CMessageEntityMuzzleFlash.class, FrameworkMessageBridge.codec(S2CMessageEntityMuzzleFlash.class), FrameworkMessageBridge.handler(S2CMessageEntityMuzzleFlash.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_gun_sound", S2CMessageGunSound.class, FrameworkMessageBridge.codec(S2CMessageGunSound.class), FrameworkMessageBridge.handler(S2CMessageGunSound.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_hot_barrel_sync", S2CMessageHotBarrelSync.class, FrameworkMessageBridge.codec(S2CMessageHotBarrelSync.class), FrameworkMessageBridge.handler(S2CMessageHotBarrelSync.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_melee_attack", S2CMessageMeleeAttack.class, FrameworkMessageBridge.codec(S2CMessageMeleeAttack.class), FrameworkMessageBridge.handler(S2CMessageMeleeAttack.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_muzzle_flash", S2CMessageMuzzleFlash.class, FrameworkMessageBridge.codec(S2CMessageMuzzleFlash.class), FrameworkMessageBridge.handler(S2CMessageMuzzleFlash.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_projectile_hit_block", S2CMessageProjectileHitBlock.class, FrameworkMessageBridge.codec(S2CMessageProjectileHitBlock.class), FrameworkMessageBridge.handler(S2CMessageProjectileHitBlock.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_projectile_hit_entity", S2CMessageProjectileHitEntity.class, FrameworkMessageBridge.codec(S2CMessageProjectileHitEntity.class), FrameworkMessageBridge.handler(S2CMessageProjectileHitEntity.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_raid_flare_burst", S2CMessageRaidFlareBurst.class, FrameworkMessageBridge.codec(S2CMessageRaidFlareBurst.class), FrameworkMessageBridge.handler(S2CMessageRaidFlareBurst.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_reload", S2CMessageReload.class, FrameworkMessageBridge.codec(S2CMessageReload.class), FrameworkMessageBridge.handler(S2CMessageReload.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_remove_projectile", S2CMessageRemoveProjectile.class, FrameworkMessageBridge.codec(S2CMessageRemoveProjectile.class), FrameworkMessageBridge.handler(S2CMessageRemoveProjectile.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_stop_beam", S2CMessageStopBeam.class, FrameworkMessageBridge.codec(S2CMessageStopBeam.class), FrameworkMessageBridge.handler(S2CMessageStopBeam.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_stop_reload", S2CMessageStopReload.class, FrameworkMessageBridge.codec(S2CMessageStopReload.class), FrameworkMessageBridge.handler(S2CMessageStopReload.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_stun_grenade", S2CMessageStunGrenade.class, FrameworkMessageBridge.codec(S2CMessageStunGrenade.class), FrameworkMessageBridge.handler(S2CMessageStunGrenade.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_sync_exo_suit_upgrades", S2CMessageSyncExoSuitUpgrades.class, FrameworkMessageBridge.codec(S2CMessageSyncExoSuitUpgrades.class), FrameworkMessageBridge.handler(S2CMessageSyncExoSuitUpgrades.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_sync_upgrade_registry", S2CMessageSyncUpgradeRegistry.class, FrameworkMessageBridge.codec(S2CMessageSyncUpgradeRegistry.class), FrameworkMessageBridge.handler(S2CMessageSyncUpgradeRegistry.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_turret_bullet_trail", S2CMessageTurretBulletTrail.class, FrameworkMessageBridge.codec(S2CMessageTurretBulletTrail.class), FrameworkMessageBridge.handler(S2CMessageTurretBulletTrail.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_update_ammo", S2CMessageUpdateAmmo.class, FrameworkMessageBridge.codec(S2CMessageUpdateAmmo.class), FrameworkMessageBridge.handler(S2CMessageUpdateAmmo.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_update_guns", S2CMessageUpdateGuns.class, FrameworkMessageBridge.codec(S2CMessageUpdateGuns.class), FrameworkMessageBridge.handler(S2CMessageUpdateGuns.class), PacketFlow.CLIENTBOUND)
                .registerPlayMessage("s2c_show_totem_animation", S2CShowTotemAnimationMessage.class, FrameworkMessageBridge.codec(S2CShowTotemAnimationMessage.class), FrameworkMessageBridge.handler(S2CShowTotemAnimationMessage.class), PacketFlow.CLIENTBOUND)
                .build();
    }

    public static FrameworkNetwork getPlayChannel() {
        return playChannel;
    }
}
